### PR TITLE
Create dialog_color_picker.xml

### PR DESCRIPTION
**Pull request by bsbachert**
color picker setup for layout-land

### CODE REVIEW

**Comment by nuclearmistake** [comment]
Adding this file to that location will not add a landscape color picker layout.

**Comment by bsbachert** [comment]
I added it to packager/apps/Settings/res/layout_land and it works fine? I
tested it..

**Comment by nuclearmistake** [comment]
The pull request doesn't have the layout file in a subdirectory of res... it's in the root.

**Comment by bsbachert** [comment]
Oh okay. .I'll get with you later so I can submit it to Gerrit properly.
Thanks Dave..

**Comment by DHOMD** [comment]
7+ months old.  Cleaning house

**Pull request closed without merging**
